# https://github.com/deoren/redmine-testing

# MariaDB/MySQL development instance

production:
  adapter: mysql2
  database: {{ mysql_database_name }}
  host:  {{ mysql_host }}
  username:  {{ mysql_user_name }}
  password:  {{ mysql_user_pass }}

development:
  adapter: mysql2
  database:  {{ mysql_database_name }}
  host:  {{ mysql_host }}
  username:  {{ mysql_user_name }}
  password:  {{ mysql_user_pass }}
